// source: google/events/cloud/firestore/v1/events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_events_cloud_firestore_v1_data_pb = require('../../../../../google/events/cloud/firestore/v1/data_pb.js');
goog.object.extend(proto, google_events_cloud_firestore_v1_data_pb);
var google_events_cloudevent_pb = require('../../../../../google/events/cloudevent_pb.js');
goog.object.extend(proto, google_events_cloudevent_pb);
goog.exportSymbol('proto.google.events.cloud.firestore.v1.DocumentCreatedEvent', null, global);
goog.exportSymbol('proto.google.events.cloud.firestore.v1.DocumentDeletedEvent', null, global);
goog.exportSymbol('proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent', null, global);
goog.exportSymbol('proto.google.events.cloud.firestore.v1.DocumentWrittenEvent', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.events.cloud.firestore.v1.DocumentCreatedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.events.cloud.firestore.v1.DocumentCreatedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.displayName = 'proto.google.events.cloud.firestore.v1.DocumentCreatedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.displayName = 'proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.events.cloud.firestore.v1.DocumentDeletedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.events.cloud.firestore.v1.DocumentDeletedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.displayName = 'proto.google.events.cloud.firestore.v1.DocumentDeletedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.events.cloud.firestore.v1.DocumentWrittenEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.events.cloud.firestore.v1.DocumentWrittenEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.displayName = 'proto.google.events.cloud.firestore.v1.DocumentWrittenEvent';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.events.cloud.firestore.v1.DocumentCreatedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: (f = msg.getData()) && google_events_cloud_firestore_v1_data_pb.DocumentEventData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.events.cloud.firestore.v1.DocumentCreatedEvent}
 */
proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.events.cloud.firestore.v1.DocumentCreatedEvent;
  return proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.events.cloud.firestore.v1.DocumentCreatedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.events.cloud.firestore.v1.DocumentCreatedEvent}
 */
proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_events_cloud_firestore_v1_data_pb.DocumentEventData;
      reader.readMessage(value,google_events_cloud_firestore_v1_data_pb.DocumentEventData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.events.cloud.firestore.v1.DocumentCreatedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_events_cloud_firestore_v1_data_pb.DocumentEventData.serializeBinaryToWriter
    );
  }
};


/**
 * optional DocumentEventData data = 1;
 * @return {?proto.google.events.cloud.firestore.v1.DocumentEventData}
 */
proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.prototype.getData = function() {
  return /** @type{?proto.google.events.cloud.firestore.v1.DocumentEventData} */ (
    jspb.Message.getWrapperField(this, google_events_cloud_firestore_v1_data_pb.DocumentEventData, 1));
};


/**
 * @param {?proto.google.events.cloud.firestore.v1.DocumentEventData|undefined} value
 * @return {!proto.google.events.cloud.firestore.v1.DocumentCreatedEvent} returns this
*/
proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.events.cloud.firestore.v1.DocumentCreatedEvent} returns this
 */
proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.events.cloud.firestore.v1.DocumentCreatedEvent.prototype.hasData = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: (f = msg.getData()) && google_events_cloud_firestore_v1_data_pb.DocumentEventData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent}
 */
proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent;
  return proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent}
 */
proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_events_cloud_firestore_v1_data_pb.DocumentEventData;
      reader.readMessage(value,google_events_cloud_firestore_v1_data_pb.DocumentEventData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_events_cloud_firestore_v1_data_pb.DocumentEventData.serializeBinaryToWriter
    );
  }
};


/**
 * optional DocumentEventData data = 1;
 * @return {?proto.google.events.cloud.firestore.v1.DocumentEventData}
 */
proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.prototype.getData = function() {
  return /** @type{?proto.google.events.cloud.firestore.v1.DocumentEventData} */ (
    jspb.Message.getWrapperField(this, google_events_cloud_firestore_v1_data_pb.DocumentEventData, 1));
};


/**
 * @param {?proto.google.events.cloud.firestore.v1.DocumentEventData|undefined} value
 * @return {!proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent} returns this
*/
proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent} returns this
 */
proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.events.cloud.firestore.v1.DocumentUpdatedEvent.prototype.hasData = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.events.cloud.firestore.v1.DocumentDeletedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: (f = msg.getData()) && google_events_cloud_firestore_v1_data_pb.DocumentEventData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.events.cloud.firestore.v1.DocumentDeletedEvent}
 */
proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.events.cloud.firestore.v1.DocumentDeletedEvent;
  return proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.events.cloud.firestore.v1.DocumentDeletedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.events.cloud.firestore.v1.DocumentDeletedEvent}
 */
proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_events_cloud_firestore_v1_data_pb.DocumentEventData;
      reader.readMessage(value,google_events_cloud_firestore_v1_data_pb.DocumentEventData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.events.cloud.firestore.v1.DocumentDeletedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_events_cloud_firestore_v1_data_pb.DocumentEventData.serializeBinaryToWriter
    );
  }
};


/**
 * optional DocumentEventData data = 1;
 * @return {?proto.google.events.cloud.firestore.v1.DocumentEventData}
 */
proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.prototype.getData = function() {
  return /** @type{?proto.google.events.cloud.firestore.v1.DocumentEventData} */ (
    jspb.Message.getWrapperField(this, google_events_cloud_firestore_v1_data_pb.DocumentEventData, 1));
};


/**
 * @param {?proto.google.events.cloud.firestore.v1.DocumentEventData|undefined} value
 * @return {!proto.google.events.cloud.firestore.v1.DocumentDeletedEvent} returns this
*/
proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.events.cloud.firestore.v1.DocumentDeletedEvent} returns this
 */
proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.events.cloud.firestore.v1.DocumentDeletedEvent.prototype.hasData = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.events.cloud.firestore.v1.DocumentWrittenEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: (f = msg.getData()) && google_events_cloud_firestore_v1_data_pb.DocumentEventData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.events.cloud.firestore.v1.DocumentWrittenEvent}
 */
proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.events.cloud.firestore.v1.DocumentWrittenEvent;
  return proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.events.cloud.firestore.v1.DocumentWrittenEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.events.cloud.firestore.v1.DocumentWrittenEvent}
 */
proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_events_cloud_firestore_v1_data_pb.DocumentEventData;
      reader.readMessage(value,google_events_cloud_firestore_v1_data_pb.DocumentEventData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.events.cloud.firestore.v1.DocumentWrittenEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_events_cloud_firestore_v1_data_pb.DocumentEventData.serializeBinaryToWriter
    );
  }
};


/**
 * optional DocumentEventData data = 1;
 * @return {?proto.google.events.cloud.firestore.v1.DocumentEventData}
 */
proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.prototype.getData = function() {
  return /** @type{?proto.google.events.cloud.firestore.v1.DocumentEventData} */ (
    jspb.Message.getWrapperField(this, google_events_cloud_firestore_v1_data_pb.DocumentEventData, 1));
};


/**
 * @param {?proto.google.events.cloud.firestore.v1.DocumentEventData|undefined} value
 * @return {!proto.google.events.cloud.firestore.v1.DocumentWrittenEvent} returns this
*/
proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.events.cloud.firestore.v1.DocumentWrittenEvent} returns this
 */
proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.events.cloud.firestore.v1.DocumentWrittenEvent.prototype.hasData = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.google.events.cloud.firestore.v1);
