// source: google/events/firebase/auth/v1/events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_events_cloudevent_pb = require('../../../../../google/events/cloudevent_pb.js');
goog.object.extend(proto, google_events_cloudevent_pb);
var google_events_firebase_auth_v1_data_pb = require('../../../../../google/events/firebase/auth/v1/data_pb.js');
goog.object.extend(proto, google_events_firebase_auth_v1_data_pb);
goog.exportSymbol('proto.google.events.firebase.auth.v1.UserCreatedEvent', null, global);
goog.exportSymbol('proto.google.events.firebase.auth.v1.UserDeletedEvent', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.events.firebase.auth.v1.UserCreatedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.events.firebase.auth.v1.UserCreatedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.events.firebase.auth.v1.UserCreatedEvent.displayName = 'proto.google.events.firebase.auth.v1.UserCreatedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.events.firebase.auth.v1.UserDeletedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.events.firebase.auth.v1.UserDeletedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.events.firebase.auth.v1.UserDeletedEvent.displayName = 'proto.google.events.firebase.auth.v1.UserDeletedEvent';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.events.firebase.auth.v1.UserCreatedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.google.events.firebase.auth.v1.UserCreatedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.events.firebase.auth.v1.UserCreatedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.firebase.auth.v1.UserCreatedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: (f = msg.getData()) && google_events_firebase_auth_v1_data_pb.AuthEventData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.events.firebase.auth.v1.UserCreatedEvent}
 */
proto.google.events.firebase.auth.v1.UserCreatedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.events.firebase.auth.v1.UserCreatedEvent;
  return proto.google.events.firebase.auth.v1.UserCreatedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.events.firebase.auth.v1.UserCreatedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.events.firebase.auth.v1.UserCreatedEvent}
 */
proto.google.events.firebase.auth.v1.UserCreatedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_events_firebase_auth_v1_data_pb.AuthEventData;
      reader.readMessage(value,google_events_firebase_auth_v1_data_pb.AuthEventData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.events.firebase.auth.v1.UserCreatedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.events.firebase.auth.v1.UserCreatedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.events.firebase.auth.v1.UserCreatedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.firebase.auth.v1.UserCreatedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_events_firebase_auth_v1_data_pb.AuthEventData.serializeBinaryToWriter
    );
  }
};


/**
 * optional AuthEventData data = 1;
 * @return {?proto.google.events.firebase.auth.v1.AuthEventData}
 */
proto.google.events.firebase.auth.v1.UserCreatedEvent.prototype.getData = function() {
  return /** @type{?proto.google.events.firebase.auth.v1.AuthEventData} */ (
    jspb.Message.getWrapperField(this, google_events_firebase_auth_v1_data_pb.AuthEventData, 1));
};


/**
 * @param {?proto.google.events.firebase.auth.v1.AuthEventData|undefined} value
 * @return {!proto.google.events.firebase.auth.v1.UserCreatedEvent} returns this
*/
proto.google.events.firebase.auth.v1.UserCreatedEvent.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.events.firebase.auth.v1.UserCreatedEvent} returns this
 */
proto.google.events.firebase.auth.v1.UserCreatedEvent.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.events.firebase.auth.v1.UserCreatedEvent.prototype.hasData = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.events.firebase.auth.v1.UserDeletedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.google.events.firebase.auth.v1.UserDeletedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.events.firebase.auth.v1.UserDeletedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.firebase.auth.v1.UserDeletedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: (f = msg.getData()) && google_events_firebase_auth_v1_data_pb.AuthEventData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.events.firebase.auth.v1.UserDeletedEvent}
 */
proto.google.events.firebase.auth.v1.UserDeletedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.events.firebase.auth.v1.UserDeletedEvent;
  return proto.google.events.firebase.auth.v1.UserDeletedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.events.firebase.auth.v1.UserDeletedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.events.firebase.auth.v1.UserDeletedEvent}
 */
proto.google.events.firebase.auth.v1.UserDeletedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_events_firebase_auth_v1_data_pb.AuthEventData;
      reader.readMessage(value,google_events_firebase_auth_v1_data_pb.AuthEventData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.events.firebase.auth.v1.UserDeletedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.events.firebase.auth.v1.UserDeletedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.events.firebase.auth.v1.UserDeletedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.firebase.auth.v1.UserDeletedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_events_firebase_auth_v1_data_pb.AuthEventData.serializeBinaryToWriter
    );
  }
};


/**
 * optional AuthEventData data = 1;
 * @return {?proto.google.events.firebase.auth.v1.AuthEventData}
 */
proto.google.events.firebase.auth.v1.UserDeletedEvent.prototype.getData = function() {
  return /** @type{?proto.google.events.firebase.auth.v1.AuthEventData} */ (
    jspb.Message.getWrapperField(this, google_events_firebase_auth_v1_data_pb.AuthEventData, 1));
};


/**
 * @param {?proto.google.events.firebase.auth.v1.AuthEventData|undefined} value
 * @return {!proto.google.events.firebase.auth.v1.UserDeletedEvent} returns this
*/
proto.google.events.firebase.auth.v1.UserDeletedEvent.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.events.firebase.auth.v1.UserDeletedEvent} returns this
 */
proto.google.events.firebase.auth.v1.UserDeletedEvent.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.events.firebase.auth.v1.UserDeletedEvent.prototype.hasData = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.google.events.firebase.auth.v1);
